version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.2.5
    command: >
      -name etcd0
      -advertise-client-urls http://etcd:2379,http://etcd:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://etcd:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster etcd0=http://etcd:2380
      -initial-cluster-state new
  memcached:
    build: memcached
    ports:
      - 22
  chronos:
    build: chronos
    ports:
      - 22
  cassandra:
    build: cassandra
    ports:
      - 22
  bono:
    build: bono
    environment:
      - PUBLIC_IP
    links:
      - sprout
    ports:
      - 22
      - "3478:3478"
      - "3478:3478/udp"
      - "5060:5060"
      - "5060:5060/udp"
      - "5062:5062"
  sprout:
    build: sprout
    links:
      - homestead
      - homer
      - ralf
      - chronos
      - memcached
    networks:
      default:
        aliases:
          - scscf.sprout
          - icscf.sprout
    ports:
      - 22
  homestead:
    build: homestead
    links:
      - cassandra
    ports:
      - 22
  homer:
    build: homer
    links:
      - cassandra
    ports:
      - 22
  ralf:
    build: ralf
    links:
      - chronos
      - memcached
    ports:
      - 22
  ellis:
    build: ellis
    links:
      - homestead
      - homer
    ports:
      - 22
      - "80:80"
