version: '2'
services:
  bono:
    build: bono
    links:
      - sprout
    ports:
      - 22
      - "3478:3478"
      - "3478:3478/udp"
      - "5060:5060"
      - "5060:5060/udp"
      - "5062:5062"
  sprout:
    build: sprout
    links:
      - homestead
      - homer
      - ralf
    ports:
      - 22
  homestead:
    build: homestead
    ports:
      - 22
  homer:
    build: homer
    ports:
      - 22
  ralf:
    build: ralf
    ports:
      - 22
  ellis:
    build: ellis
    links:
      - homestead
      - homer
    ports:
      - 22
      - "80:80"

