apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: ellis
  name: ellis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ellis
    spec:
      containers:
      - image: "clearwater/ellis:latest"
        name: ellis
        ports:
        - containerPort: 22
        - containerPort: 80
        env:
        - name: ZONE
          value: ZONE_VALUE
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 80
      restartPolicy: Always
