apiVersion: v1
kind: Service
metadata:
  name: ellis
spec:
  type: NodePort
  #type: LoadBalancer
  #loadBalancerIP: 104.199.68.94
  ports:
  - name: "http"
    nodePort: 0
    port: 80
  selector:
    service: ellis
