apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    service: ellis
  name: ellis
  namespace: default
spec:
  replicas: 1
  selector:
    service: ellis
  template:
    metadata:
      labels:
        service: ellis
    spec:
      containers:
      - image: "clearwater/ellis:latest"
        name: ellis
        ports:
        - containerPort: 22
        - containerPort: 80
        env:
        - name: ZONE
          value: ZONE_VALUE
      restartPolicy: Always
