apiVersion: v1
kind: Service
metadata:
  name: ellis
  namespace: default
spec:
  ports:
  - name: "http"
    nodePort: 0
    port: 80
    protocol: ""
    targetPort: 0
  selector:
    service: ellis
