apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: homestead
  name: homestead
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: homestead
    spec:
      containers:
      - image: "clearwater/homestead:latest"
        name: homestead
        ports:
        - containerPort: 22
        - containerPort: 8888
        - containerPort: 8889
        env:
        - name: ZONE
          value: ZONE_VALUE
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888 8889"]
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888 8889"]
      restartPolicy: Always
