apiVersion: v1
kind: Service
metadata:
  name: homer
  namespace: default
spec:
  ports:
  - name: "7888"
    nodePort: 0
    port: 7888
    protocol: ""
    targetPort: 0
  selector:
    service: homer
