apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: memcached
  name: memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: memcached
    spec:
      containers:
      - image: "clearwater/memcached:latest"
        name: memcached
        ports:
        - containerPort: 22
        - containerPort: 11211
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 11211
      restartPolicy: Always
