apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: ralf
  name: ralf
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ralf
    spec:
      containers:
      - image: "clearwater/ralf:latest"
        name: ralf
        ports:
        - containerPort: 22
        - containerPort: 10888
        env:
        - name: ZONE
          value: ZONE_VALUE
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 10888
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 10888
      restartPolicy: Always
